### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by LeD0c4** [cedr0u/housing#1]
Hi, 
I would like to know if i'm the only one with "this" overlay ? i'dont know if it's a bug or anything else. It's supposed to be here ?
![Capture d'écran 2023-05-26 101820](https://github.com/cedr0u/housing/assets/95167587/5e4a0422-0448-400b-add3-0f3bb3ac0c0d)

**Comment by cedr0u** [comment]
Hello,
indeed the translation key is bugged i'll try to fix it,
What is the language of your game?

**Comment by cedr0u** [comment]
updated problem solved
